Repository jkkostrzewski/zzpj-project, pull requests merged in 2020-06, with the labels that each got.

#24 add managing shop stats;
  src/main/java/com/zachaczcompany/zzpj/commons/response/Error.java
  src/main/java/com/zachaczcompany/zzpj/commons/response/Response.java
  src/main/java/com/zachaczcompany/zzpj/commons/response/Success.java
  src/main/java/com/zachaczcompany/zzpj/security/annotations/CanEditQueue.java
  src/main/java/com/zachaczcompany/zzpj/security/annotations/CanEditShop.java
  src/main/java/com/zachaczcompany/zzpj/security/annotations/IsOwner.java
  src/main/java/com/zachaczcompany/zzpj/security/auth/database/UserEntity.java
  src/main/java/com/zachaczcompany/zzpj/security/jwt/RegistrationController.java
  src/main/java/com/zachaczcompany/zzpj/security/jwt/UserRegistrationService.java
  src/main/java/com/zachaczcompany/zzpj/shops/ShopController.java
  src/main/java/com/zachaczcompany/zzpj/shops/ShopFacade.java
  src/main/java/com/zachaczcompany/zzpj/shops/ShopOutputDto.java
  src/main/java/com/zachaczcompany/zzpj/shops/ShopService.java
  src/main/java/com/zachaczcompany/zzpj/shops/ShopStatsDto.java
  src/main/java/com/zachaczcompany/zzpj/shops/StatisticsUpdateDto.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/Address.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/DailyOpenHours.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/Localization.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/OpenHours.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/Shop.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopController.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopDetails.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopFacade.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopFilterCriteria.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopRepository.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopService.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopStats.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/StockType.java
  src/main/java/com/zachaczcompany/zzpj/shops/exceptions/IllegalShopOperation.java
  src/test/groovy/com/zachaczcompany/zzpj/shops/domain/ShopServiceSpec.groovy
  src/test/groovy/com/zachaczcompany/zzpj/shops/domain/ShopTestsDataProvider.groovy
Labels: enhancement

#25 Opinions added
  src/main/java/com/zachaczcompany/zzpj/shops/OpinionDto.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/Opinion.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/OpinionController.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/OpinionRepository.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/OpinionService.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopFacade.java
Labels: enhancement

#28 Search history
  src/main/java/com/zachaczcompany/zzpj/commons/response/Error.java
  src/main/java/com/zachaczcompany/zzpj/commons/response/Response.java
  src/main/java/com/zachaczcompany/zzpj/commons/response/Success.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopController.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopFacade.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopFilterCriteria.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopSearch.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopSearchRepository.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopService.java
  src/test/groovy/com/zachaczcompany/zzpj/shops/domain/ShopFacadeSpec.groovy
  src/test/groovy/com/zachaczcompany/zzpj/shops/domain/ShopServiceSpec.groovy
  src/test/groovy/com/zachaczcompany/zzpj/shops/domain/ShopTestsDataProvider.groovy
Labels: enhancement

#34 Banner added
  src/main/resources/banner.txt
Labels: documentation

#38 fix sign up;
  src/main/java/com/zachaczcompany/zzpj/security/jwt/CreatedUserDto.java
  src/main/java/com/zachaczcompany/zzpj/security/jwt/UserRegistrationService.java
Labels: bug

#36 Add swagger together with description adnotations in controllers and dto
  pom.xml
  src/main/java/com/zachaczcompany/zzpj/security/OwnerSignUpDto.java
  src/main/java/com/zachaczcompany/zzpj/security/configuration/SecurityConfig.java
  src/main/java/com/zachaczcompany/zzpj/security/configuration/SwaggerConfig.java
  src/main/java/com/zachaczcompany/zzpj/security/jwt/RegistrationController.java
  src/main/java/com/zachaczcompany/zzpj/security/jwt/UserSignUp.java
  src/main/java/com/zachaczcompany/zzpj/shops/OpinionDto.java
  src/main/java/com/zachaczcompany/zzpj/shops/ShopController.java
  src/main/java/com/zachaczcompany/zzpj/shops/ShopCreateDto.java
  src/main/java/com/zachaczcompany/zzpj/shops/ShopOutputDto.java
  src/main/java/com/zachaczcompany/zzpj/shops/ShopStatsDto.java
  src/main/java/com/zachaczcompany/zzpj/shops/StatisticsUpdateDto.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/OpinionController.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopService.java
Labels: documentation, enhancement

#31 Opinion test
  src/main/java/com/zachaczcompany/zzpj/shops/domain/Opinion.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/OpinionController.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/OpinionService.java
  src/test/groovy/com/zachaczcompany/zzpj/shops/domain/OpinionServiceSpec.groovy
Labels: bug, enhancement

#39 Stats history
  src/main/java/com/zachaczcompany/zzpj/commons/DateTimeHelper.java
  src/main/java/com/zachaczcompany/zzpj/history/shopStats/ShopStatsChangedEvent.java
  src/main/java/com/zachaczcompany/zzpj/history/shopStats/ShopStatsController.java
  src/main/java/com/zachaczcompany/zzpj/history/shopStats/ShopStatsDiff.java
  src/main/java/com/zachaczcompany/zzpj/history/shopStats/ShopStatsMemento.java
  src/main/java/com/zachaczcompany/zzpj/history/shopStats/ShopStatsMementoRepository.java
  src/main/java/com/zachaczcompany/zzpj/history/shopStats/ShopStatsMementoService.java
  src/main/java/com/zachaczcompany/zzpj/shops/StatisticsUpdateDto.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/Shop.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopFacade.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopService.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopStats.java
  src/test/groovy/com/zachaczcompany/zzpj/shops/domain/ShopFacadeSpec.groovy
  src/test/groovy/com/zachaczcompany/zzpj/shops/domain/ShopServiceSpec.groovy
Labels: enhancement

#40 Localization now from api when creating shop
  src/main/java/com/zachaczcompany/zzpj/shops/ShopCreateDto.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/LocalizationApiStrategy.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/LocalizationDefaultStrategy.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/LocalizationStrategy.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopFacade.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopService.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/location/ApartmentLocation.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/location/BuildingLocation.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/location/CityLocation.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/location/Location.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/location/LocationDecorator.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/location/NameLocation.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/location/StreetLocation.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/location/ZipCodeLocation.java
  src/main/java/com/zachaczcompany/zzpj/shops/exceptions/LocationNotFoundException.java
  src/test/groovy/com/zachaczcompany/zzpj/shops/domain/ShopFacadeSpec.groovy
  src/test/groovy/com/zachaczcompany/zzpj/shops/domain/ShopServiceSpec.groovy
Labels: enhancement

#44 add /shops put method
  src/main/java/com/zachaczcompany/zzpj/shops/ShopController.java
  src/main/java/com/zachaczcompany/zzpj/shops/ShopUpdateDto.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/Shop.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopDetails.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopFacade.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopService.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopValidator.java
  src/test/groovy/com/zachaczcompany/zzpj/shops/domain/ShopServiceSpec.groovy
  src/test/groovy/com/zachaczcompany/zzpj/shops/domain/ShopTestsDataProvider.groovy
Labels: enhancement

#47 Owner and employee
  src/main/java/com/zachaczcompany/zzpj/security/annotations/IsEmployee.java
  src/main/java/com/zachaczcompany/zzpj/security/jwt/RegistrationController.java
  src/main/java/com/zachaczcompany/zzpj/security/jwt/UserRegistrationService.java
  src/main/java/com/zachaczcompany/zzpj/security/jwt/exceptions/UserNotAllowedToPerform.java
Labels: enhancement

#46 filtering shops by distance;
  src/main/java/com/zachaczcompany/zzpj/commons/CommonExceptionHandler.java
  src/main/java/com/zachaczcompany/zzpj/distance/DistanceCalculationConfiguration.java
  src/main/java/com/zachaczcompany/zzpj/distance/DistanceCalculationStrategy.java
  src/main/java/com/zachaczcompany/zzpj/distance/DistanceCalculator.java
  src/main/java/com/zachaczcompany/zzpj/distance/DistanceService.java
  src/main/java/com/zachaczcompany/zzpj/distance/LocationApiDistance.java
  src/main/java/com/zachaczcompany/zzpj/distance/StraightLineDistance.java
  src/main/java/com/zachaczcompany/zzpj/location/model/Route.java
  src/main/java/com/zachaczcompany/zzpj/location/model/RoutingResponse.java
  src/main/java/com/zachaczcompany/zzpj/shops/ShopController.java
  src/main/java/com/zachaczcompany/zzpj/shops/ShopWithDistanceOutputDto.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/DailyOpenHours.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/DistanceCriteria.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/Localization.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopFacade.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopFilterCriteria.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopService.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/location/ApartmentLocation.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/location/BuildingLocation.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/location/CityLocation.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/location/NameLocation.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/location/StreetLocation.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/location/ZipCodeLocation.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/validation/distance/DistanceCriteriaValidator.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/validation/distance/ValidDistanceCriteria.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/validation/openHours/OpenHoursListValidator.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/validation/openHours/OpenHoursValidationRule.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/validation/openHours/OpenHoursValidator.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/validation/openHours/ValidOpenHours.java
  src/main/resources/application.yml
  src/test/groovy/com/zachaczcompany/zzpj/distance/CalculationStrategySpec.groovy
  src/test/groovy/com/zachaczcompany/zzpj/distance/DistanceServiceSpec.groovy
  src/test/groovy/com/zachaczcompany/zzpj/distance/DistanceTestDataProvider.groovy
  src/test/groovy/com/zachaczcompany/zzpj/distance/LocationTestDataProvider.groovy
  src/test/groovy/com/zachaczcompany/zzpj/shops/domain/ShopFacadeSpec.groovy
  src/test/groovy/com/zachaczcompany/zzpj/shops/domain/ShopServiceSpec.groovy
  src/test/groovy/com/zachaczcompany/zzpj/shops/domain/ShopTestsDataProvider.groovy
Labels: enhancement

#48 add email notifications
  pom.xml
  src/main/java/com/zachaczcompany/zzpj/commons/response/Error.java
  src/main/java/com/zachaczcompany/zzpj/shops/ShopController.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/NotificationList.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/NotificationListRepository.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/NotificationService.java
  src/main/java/com/zachaczcompany/zzpj/shops/domain/ShopService.java
  src/main/resources/application.yml
  src/main/resources/templates/emailNotificationTemplate.html
  src/test/groovy/com/zachaczcompany/zzpj/shops/domain/ShopFacadeSpec.groovy
  src/test/groovy/com/zachaczcompany/zzpj/shops/domain/ShopServiceSpec.groovy
Labels: enhancement

#51 Swagger adnotations added
  src/main/java/com/zachaczcompany/zzpj/history/shopStats/ShopStatsController.java
  src/main/java/com/zachaczcompany/zzpj/reports/ReportsController.java
Labels: documentation
